updated deploy directus check snapshot

diff --git a/.github/workflows/deploy-directus.yml b/.github/workflows/deploy-directus.yml
--- a/.github/workflows/deploy-directus.yml
+++ b/.github/workflows/deploy-directus.yml
@@ -68,5 +68,14 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
           script: |
+            if [ -d ./merlaart-directus/snapshot ]; then
+              echo "Snapshot directory exists."
+              ls -la ./merlaart-directus/snapshot
+            else
+              echo "Error: Snapshot directory does not exist."
+              exit 1
+            fi
+
+           
             docker cp ./merlaart-directus/snapshot directus_app:/snapshot
             docker exec directus_app npx directus schema apply /snapshot
